language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  provider: heroku
  edge: true
  api_key:
    secure: C+mKzrhLWxlmBA05daPc0U1U0cJ8XQjN/PhVkuxKmWjJHngheLibMYJMYcKHkJqS7USqifb9Ix3kS29lFWbcqIbsf7O+f478bNNtzRz5VBGSmPIr1GoFHHnixqoIMZBxza2asvIuHyZejuOZeMHpm+iiQmpXXsRoN2jI13Kra5geG5TjCKyieFbdjmtBzuxiap3x3nkMP7Buc6yFyKIZGgb2BMrltIlXUX0cLN9ryeEXIENgpEnMjYQ4iVr+FRWNDzRL+J4EvmfQOcOSZQPv+zMADSW2LuQeqEgV7loYMdjg5F+w0SAxl9bJ4xNe6W55TprmUoN+0uxzGCO/7T+EBeQHBqam5bjEmX5kTdwBaIet4jcFQHrL+OIC9N1oz8OKkD3sKC+sHaBc8BRXSKuOOvdofEhZ0HAAh5WzWhFDUgtELL1Uzv7vPEA9I3sWsYtrAOBq7Jn/BzcwZISGcjqF5zkivmdfgCcxxMFePuJZHEw+VqUUZbAi0qjmIsRUB26XuZquZFW6XhxaYc+2q0l1aGzoVAI3pB9SHACws5g383FIva2zK8Ip9ZaHD4sPhMiJN/wU2NfKW0VvTXcExKOVt/hRaoX1zglHsocLHqL2N8KD3ji/McOXLeqGSxlyVYEel4IqnpuV/B1xOQZG6FZcIbX1GMpjLNfaCJRMCJCG7kg=
