language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  provider: heroku
  api_key:
    secure: oGJzB8AjifNpctl9D1Gj0DcmahmkPTQvuVHv4kkC9Yx8/p66zYZ8Oy1jn9MHk3+3xQz81JRYVIzzzpkrRTTU1A9WiadOJkmY/BEWHajbhYbQz/W9NmQsBYqdSbB8pm265wEBa/MBJE+/VCMGKMJ3kRatGMryLkoXoP3ia5yCvQ9moewNYfv+obqLkeMmi3bJBGDGTttVLXO4S2TqP/8PTF9/6w+CJDWKTyLetk5q9pr8MoUerr9q4ZuoEBwYejr6DMot25oT1R5X4u/ybaIEncHvxMRqgLmUxnmgBC9nyN2END8LqMWj8dqMekDFm1xJ4Gu354mOjrw20oRrY8LphFmRSTXvtp6um4oJ0pBxJ6ggHSSV/REGTx1W8j/4KnCBSJ/Du1OzUBfLPctjbtQJr2C1afUUXiJ0d77qQWgxkNtjgb8V/1MqpqJ6pL00TFv4YwPcXuJVPmr6nWIh3cVabjG2mOYcpEoQwjKgosP8+BZ1/yeQp3E1FKlaS863q4uyRMR3estIiOTX4QhHTZsPt7ABQjkAcfsHwm3vRsr+3iSOAYhz/tAJkwg//bmACHT3gPXQwTCNxMIfrnzpFvv/HdElJYPYLBTP3vgviDgsbzGCbALZpn4fSUHI7SZ8AyLLKnVglM1gOCCRGQ/YZ3ZaqKun58QEZcJ8WprW6PjtFSg=
  app: app12134